spring.application.name=tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/tracker
spring.datasource.username=danielmeletoyitan
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
